name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: myralla
          POSTGRES_PASSWORD: myralla
          POSTGRES_DB: myralla
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U myralla"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up environment
        run: |
          echo "SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/myralla" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_USERNAME=myralla" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_PASSWORD=myralla" >> $GITHUB_ENV
          echo "SPRING_REDIS_HOST=localhost" >> $GITHUB_ENV
          echo "SPRING_REDIS_PORT=6379" >> $GITHUB_ENV

      - name: Install dependencies
        run: ./mvnw dependency:resolve

      - name: Run tests
        run: ./mvnw test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image with unique tag
        if: success()
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/myralla-core:latest
            ${{ secrets.DOCKER_USERNAME }}/myralla-core:${{ github.sha }}

      - name: Logout from Docker Hub
        run: docker logout
